# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 18:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Project Name')),
                ('website', models.CharField(max_length=200, validators=[django.core.validators.URLValidator()], verbose_name=b'Project Website')),
                ('img_location', models.CharField(max_length=200, verbose_name=b'Project Image Location')),
                ('short_description', models.TextField(max_length=2000, verbose_name=b'Project Short Description')),
                ('long_description', models.TextField(verbose_name=b'Project Long Description')),
                ('highlight', models.BooleanField(default=False, verbose_name=b'Highlight')),
                ('highlight_order', models.SmallIntegerField(verbose_name=b'Order on highlights')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-modified_date'],
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Techs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_type', models.CharField(max_length=50, verbose_name=b'Technology Used')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tech', to='projects.Projects')),
            ],
            options={
                'verbose_name_plural': 'Techs',
            },
        ),
    ]
