# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 18:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Contact Name')),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator(message=b'Invalid entry. Enter a valid email address.')], verbose_name=b'Email')),
                ('phone', models.CharField(max_length=14, verbose_name=b'Phone')),
                ('message', models.TextField(max_length=2000, verbose_name=b'Message')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
