# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-18 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name=b'Job Title')),
                ('employer', models.CharField(max_length=100, verbose_name=b'Employer')),
                ('start_date', models.CharField(max_length=100, verbose_name=b'Start Date')),
                ('end_date', models.CharField(max_length=100, verbose_name=b'End Date')),
                ('order', models.SmallIntegerField(verbose_name=b'Order on website')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
                'verbose_name_plural': 'Job Experience',
            },
        ),
    ]
