# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-18 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(default='text', verbose_name=b'Description'),
            preserve_default=False,
        ),
    ]
