# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='category',
            field=models.IntegerField(choices=[(1, b'Design'), (2, b'Back-end'), (3, b'Front-end'), (4, b'Data analysis')], verbose_name=b'Category'),
        ),
    ]
